import { IsString, Length } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class VerifyMfaDto {
  @ApiProperty({ description: 'The 6-digit TOTP code generated by the authenticator app' })
  @IsString()
  @Length(6, 6)
  code: string;
}
